# Generated by Django 5.1.5 on 2025-03-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('dry', 'Dry'), ('wet', 'Wet')], max_length=50)),
                ('ingredients', models.TextField()),
                ('age_group', models.CharField(choices=[('kitten', 'Kitten'), ('adult', 'Adult'), ('senior', 'Senior')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
